/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ApiPlansRouteImport } from './routes/api.plans'
import { Route as PlansIdRouteImport } from './routes/plans.$id'
import { Route as ApiPlansIdRouteImport } from './routes/api.plans.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlansRoute = ApiPlansRouteImport.update({
  id: '/api/plans',
  path: '/api/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansIdRoute = PlansIdRouteImport.update({
  id: '/plans/$id',
  path: '/plans/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlansIdRoute = ApiPlansIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPlansRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/health': typeof HealthRoute
  '/api/plans': typeof ApiPlansRouteWithChildren
  '/plans/$id': typeof PlansIdRoute
  '/api/plans/$id': typeof ApiPlansIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/health': typeof HealthRoute
  '/api/plans': typeof ApiPlansRouteWithChildren
  '/plans/$id': typeof PlansIdRoute
  '/api/plans/$id': typeof ApiPlansIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/health': typeof HealthRoute
  '/api/plans': typeof ApiPlansRouteWithChildren
  '/plans/$id': typeof PlansIdRoute
  '/api/plans/$id': typeof ApiPlansIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-docs'
    | '/health'
    | '/api/plans'
    | '/plans/$id'
    | '/api/plans/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-docs'
    | '/health'
    | '/api/plans'
    | '/plans/$id'
    | '/api/plans/$id'
  id:
    | '__root__'
    | '/'
    | '/api-docs'
    | '/health'
    | '/api/plans'
    | '/plans/$id'
    | '/api/plans/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDocsRoute: typeof ApiDocsRoute
  HealthRoute: typeof HealthRoute
  ApiPlansRoute: typeof ApiPlansRouteWithChildren
  PlansIdRoute: typeof PlansIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plans': {
      id: '/api/plans'
      path: '/api/plans'
      fullPath: '/api/plans'
      preLoaderRoute: typeof ApiPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/$id': {
      id: '/plans/$id'
      path: '/plans/$id'
      fullPath: '/plans/$id'
      preLoaderRoute: typeof PlansIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plans/$id': {
      id: '/api/plans/$id'
      path: '/$id'
      fullPath: '/api/plans/$id'
      preLoaderRoute: typeof ApiPlansIdRouteImport
      parentRoute: typeof ApiPlansRoute
    }
  }
}

interface ApiPlansRouteChildren {
  ApiPlansIdRoute: typeof ApiPlansIdRoute
}

const ApiPlansRouteChildren: ApiPlansRouteChildren = {
  ApiPlansIdRoute: ApiPlansIdRoute,
}

const ApiPlansRouteWithChildren = ApiPlansRoute._addFileChildren(
  ApiPlansRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDocsRoute: ApiDocsRoute,
  HealthRoute: HealthRoute,
  ApiPlansRoute: ApiPlansRouteWithChildren,
  PlansIdRoute: PlansIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
